# yaml-language-server: $schema=../../vendor/symfony/dependency-injection/Loader/schema/services.schema.json
nelmio_cors:
    defaults:
        origin_regex: false
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'X-Request-ID']
        allow_credentials: false
        max_age: 3600
    paths:
        '^/api/':
            allow_credentials: false

when@dev:
    nelmio_cors:
        paths:
            '^/api/':
                allow_origin: ['*']
                allow_credentials: false


#when@prod:
#    nelmio_cors:
#        paths:
#            '^/api/':
#                allow_credentials: true
