<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260408075450 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Database baseline with PostgreSQL fulltext search support.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE album (owner_uuid UUID NOT NULL, title VARCHAR(255) NOT NULL, artist VARCHAR(255) NOT NULL, release_year INT DEFAULT NULL, format VARCHAR(255) NOT NULL, is_favorite BOOLEAN NOT NULL, genre VARCHAR(255) DEFAULT NULL, label VARCHAR(255) DEFAULT NULL, cover_url VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, uuid UUID NOT NULL, PRIMARY KEY (uuid))');
        $this->addSql('CREATE TABLE app_user (password VARCHAR(255) NOT NULL, roles JSON NOT NULL, email VARCHAR(180) NOT NULL, uuid UUID NOT NULL, PRIMARY KEY (uuid))');
        $this->addSql('CREATE UNIQUE INDEX uq_email ON app_user (email)');
        $this->addSql('CREATE TABLE external_reference (platform VARCHAR(255) NOT NULL, external_id VARCHAR(255) NOT NULL, metadata JSON DEFAULT NULL, uuid UUID NOT NULL, album_uuid UUID NOT NULL, PRIMARY KEY (uuid))');
        $this->addSql('CREATE INDEX IDX_8AF8E607B574E6E6 ON external_reference (album_uuid)');
        $this->addSql('CREATE UNIQUE INDEX uq_album_platform_external_id ON external_reference (album_uuid, platform, external_id)');
        $this->addSql('CREATE TABLE refresh_tokens (refresh_token VARCHAR(128) NOT NULL, username VARCHAR(255) NOT NULL, valid TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9BACE7E1C74F2195 ON refresh_tokens (refresh_token)');
        $this->addSql('ALTER TABLE external_reference ADD CONSTRAINT FK_8AF8E607B574E6E6 FOREIGN KEY (album_uuid) REFERENCES album (uuid) ON DELETE CASCADE');

        // --- PostgreSQL full-text search (outside Doctrine Mapping) ---
        $this->addSql("
          ALTER TABLE album ADD COLUMN search_vector tsvector GENERATED ALWAYS AS (
              setweight(to_tsvector('simple', coalesce(title, '')), 'A') ||
              setweight(to_tsvector('simple', coalesce(artist, '')), 'A') ||
              setweight(to_tsvector('simple', coalesce(label, '')), 'B')
          ) STORED
      ");
        $this->addSql('CREATE INDEX search_vector_idx ON album USING GIN (search_vector)');
    }
}
