App\Collection\App\Command\AddAlbumCommand:
    properties:
        ownerUuid:
            - NotNull: ~
        title:
            - NotBlank: ~
            - Length:
                max: 255
        artist:
            - NotBlank: ~
            - Length:
                max: 255
        releaseYear:
            - Type:
                type: integer
            - Range:
                min: 1900
                max: 2100
        format:
            - NotBlank: ~
            - Length:
                max: 255
        isFavorite:
            - Type:
                type: boolean
        genre:
            - Length:
                max: 100
        label:
            - Length:
                max: 255
        coverUrl:
            - Url:
                requireTld: true
