App\User\App\Command\UpdateUserCommand:
    properties:
        uuid:
            - NotNull: ~
        requesterUuid:
            - NotNull: ~
        password:
            - Length:
                  max: 180
        roles:
            - Type: array
        email:
            - NotNull: ~
            - Email:
                  message: The email "{{ value }}" is not a valid email.
