App\Collection\App\Query\FindExternalReferencesQuery:
    properties:
        page:
            - Type: integer
            - GreaterThanOrEqual: 1
        limit:
            - Type: integer
            - Range:
                    min: 1
                    max: 100
