App\Collection\App\Query\FindAlbumsByOwnerQuery:
    properties:
        ownerUuid:
            - NotNull: ~
        requesterUuid:
          - NotNull: ~
        isAdmin:
          - Type: bool
          - NotNull: ~
        sortBy:
            - Choice:
                choices: [ title, artist, genre, releaseYear, format, label ]
                message: Choose a valid sort field.
        sortOrder:
            - Choice:
                choices: [ ASC, DESC ]
                message: Choose a valid sort order.
        genre:
            - Type: string
