App\Collection\App\Query\FindAlbumsByOwnerWithPaginationQuery:
    properties:
        ownerUuid:
            - NotNull: ~
        requesterUuid:
          - NotNull: ~
        isAdmin:
          - Type: bool
          - NotNull: ~
        sortBy:
            - Choice:
                choices: [ title, artist, genre, releaseYear, format, label ]
                message: Choose a valid sort field.
        sortOrder:
            - Choice:
                choices: [ ASC, DESC ]
                message: Choose a valid sort order.
        isFavorite:
            - Type:
                  type: boolean
        genre:
            - Type: string
        search:
            - Type: string
            - NotBlank:
                  allowNull: true
        artist:
            - Type: string
        label:
            - Type: string
        format:
            - Type: string
        yearFrom:
            - Type: integer
            - Range: { min: 1900, max: 2100 }
        yearTo:
            - Type: integer
            - Range: { min: 1900, max: 2100 }
    # Custom validation
    constraints:
        - App\Collection\Infra\Validator\SearchAndSortIncompatible: ~
